/*
 * src/backends/vulkan/pipelines.c — compute-pipeline creation.
 *
 * Layer: BACKEND (vulkan).
 */
#include "vk_internal.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

/* SPIR-V blobs (generated by `make vulkan-shaders`); only this file uses them.
 * One per vk_pipes.def row: a row whose header is missing here does not
 * compile, a header no row names warns as an unused variable. */
#include "shaders/act_quant_i8_f32_spv.h"
#include "shaders/add_f32_spv.h"
#include "shaders/argmax_f32_spv.h"
#include "shaders/attention_f16_cm_spv.h"
#include "shaders/attention_f16_hd128_cm_spv.h"
#include "shaders/attention_f16_hd512_cm_spv.h"
#include "shaders/attention_f16_spv.h"
#include "shaders/attention_f32_spv.h"
#include "shaders/attn_comb_spv.h"
#include "shaders/attn_part_f16_spv.h"
#include "shaders/deltanet_conv_f32_spv.h"
#include "shaders/deltanet_delta_f32_spv.h"
#include "shaders/deltanet_norm_f32_spv.h"
#include "shaders/deltanet_scan_f32_spv.h"
#include "shaders/embed_lookup_scaled_spv.h"
#include "shaders/ffn_gate_up_gelu_q4k_spv.h"
#include "shaders/ffn_norm_gate_up_q4k_spv.h"
#include "shaders/gelu_tanh_f32_spv.h"
#include "shaders/gelu_tanh_mul_f32_spv.h"
#include "shaders/hadamard_f32_spv.h"
#include "shaders/kv_append_f16_spv.h"
#include "shaders/matmul_f32_spv.h"
#include "shaders/matmul_pq2_0_f32acc_cm_spv.h"
#include "shaders/matmul_pq2_0_t64_cm_spv.h"
#include "shaders/matmul_pq2_0_cm_spv.h"
#include "shaders/matmul_pq2_0_spv.h"
#include "shaders/matmul_q4_0_spv.h"
#include "shaders/matmul_q4_1_spv.h"
#include "shaders/matmul_q4k_cm32_spv.h"
#include "shaders/matmul_q4k_cm_spv.h"
#include "shaders/matmul_q6k_t128_cm_spv.h"
#include "shaders/matmul_q5k_cm_spv.h"
#include "shaders/matmul_q4k_spv.h"
#include "shaders/matmul_q4k_t128_cm_spv.h"
#include "shaders/matmul_q5k_spv.h"
#include "shaders/matmul_q6k_cm_spv.h"
#include "shaders/matmul_q6k_spv.h"
#include "shaders/matmul_q8_0_cm_spv.h"
#include "shaders/matmul_q4_0_cm_spv.h"
#include "shaders/matmul_tq2_0_cm_spv.h"
#include "shaders/matmul_tq2_0_t128_cm_spv.h"
#include "shaders/matmul_q4_1_cm_spv.h"
#include "shaders/matmul_q8_0_spv.h"
#include "shaders/matmul_tq2_0_spv.h"
#include "shaders/matvec_f32_spv.h"
#include "shaders/matvec_pq2_0_spv.h"
#include "shaders/matvec_q4_0_spv.h"
#include "shaders/matvec_q4_1_spv.h"
#include "shaders/matvec_q4k_spv.h"
#include "shaders/matvec_q5k_spv.h"
#include "shaders/matvec_q6k_spv.h"
#include "shaders/matvec_q8_0_spv.h"
#include "shaders/matvec_tq2_0_spv.h"
#include "shaders/mul_f32_spv.h"
#include "shaders/ple_gate_f32_spv.h"
#include "shaders/qgate_split_f32_spv.h"
#include "shaders/qkv_prep_f16_spv.h"
#include "shaders/qkv_prep_f32_spv.h"
#include "shaders/relu2_f32_spv.h"
#include "shaders/rmsnorm_add_f32_spv.h"
#include "shaders/rmsnorm_f32_spv.h"
#include "shaders/rope_f32_spv.h"
#include "shaders/scale_f32_spv.h"
#include "shaders/sigmoid_mul_f32_spv.h"
#include "shaders/silu_f32_spv.h"
#include "shaders/silu_mul_f32_spv.h"

/* local_size_x of a compute module (OpExecutionMode LocalSize), 0 when the
 * module does not state a literal one. */
static uint32_t vk_spirv_local_size_x(size_t n_words, const uint32_t code[static n_words]) {
    static constexpr uint32_t OP_EXECUTION_MODE = 16;
    static constexpr uint32_t MODE_LOCAL_SIZE   = 17;
    for (size_t i = 5; i < n_words;) {
        const uint32_t n_op = code[i] >> 16, op = code[i] & 0xffffu;
        if (n_op == 0 || n_op > n_words - i) {
            return 0;
        }
        if (op == OP_EXECUTION_MODE && n_op >= 6 && code[i + 2] == MODE_LOCAL_SIZE) {
            return code[i + 3];
        }
        i += n_op;
    }
    return 0;
}

[[nodiscard]] static enum geist_status vk_make_pipeline(struct geist_backend *be,
                                                        struct vk_state      *st,
                                                        const uint32_t       *code,
                                                        size_t                code_bytes,
                                                        VkPipelineLayout      layout,
                                                        bool                  pin_sg32,
                                                        VkPipeline           *out) {
    VkShaderModuleCreateInfo minfo = {.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
                                      .codeSize = code_bytes,
                                      .pCode    = code};
    VkShaderModule           mod   = VK_NULL_HANDLE;
    if (st->fn.CreateShaderModule(st->device, &minfo, nullptr, &mod) != VK_SUCCESS) {
        geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: shader module creation failed");
        return GEIST_E_BACKEND;
    }
    VkPipelineShaderStageRequiredSubgroupSizeCreateInfo sg32 = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO,
            .requiredSubgroupSize = 32};
    VkComputePipelineCreateInfo pinfo = {
            .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
            .stage = {.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                      .pNext = pin_sg32 ? &sg32 : nullptr,
                      .flags = pin_sg32 ? VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT
                                        : 0u,
                      .stage = VK_SHADER_STAGE_COMPUTE_BIT,
                      .module = mod,
                      .pName  = "main"},
            .layout = layout};
    VkResult r = st->fn.CreateComputePipelines(st->device, st->pcache, 1, &pinfo, nullptr, out);
    st->fn.DestroyShaderModule(st->device, mod, nullptr);
    if (r != VK_SUCCESS) {
        geist_backend_set_error(
                be, GEIST_E_BACKEND, "vulkan: compute pipeline failed (%d)", (int) r);
        return GEIST_E_BACKEND;
    }
    return GEIST_OK;
}

/* The pipeline cache file: GEIST_VK_PIPELINE_CACHE names it ("0" turns the
 * cache off); else $XDG_CACHE_HOME/geist or ~/.cache/geist, one file per
 * driver build (pipelineCacheUUID), so a driver update starts a new one. The
 * driver validates the header of what it is given, and a cache it rejects
 * only costs the compile. false: no cache. */
static bool vk_pcache_path(const struct vk_state *st, size_t n, char path[static n]) {
    const char *env = getenv("GEIST_VK_PIPELINE_CACHE");
    if (env != nullptr) {
        return strcmp(env, "0") != 0 && env[0] != '\0' && (size_t) snprintf(path, n, "%s", env) < n;
    }
    char        dir[1024];
    const char *xdg  = getenv("XDG_CACHE_HOME");
    const char *home = getenv("HOME");
    int         w    = xdg != nullptr && xdg[0] != '\0' ? snprintf(dir, sizeof dir, "%s/geist", xdg)
                       : home != nullptr && home[0] != '\0'
                               ? snprintf(dir, sizeof dir, "%s/.cache/geist", home)
                               : -1;
    if (w < 0 || (size_t) w >= sizeof dir) {
        return false;
    }
    /* ponytail: one level of mkdir; a missing ~/.cache just means no cache */
    (void) mkdir(dir, 0755);
    char uuid[2 * VK_UUID_SIZE + 1];
    for (size_t i = 0; i < VK_UUID_SIZE; ++i) {
        snprintf(uuid + 2 * i, 3, "%02x", st->pcache_uuid[i]);
    }
    w = snprintf(path, n, "%s/vulkan-pipelines-%s.bin", dir, uuid);
    return w > 0 && (size_t) w < n;
}

/* Creates st->pcache from the file, if any (a missing or unreadable file is
 * an empty cache). Returns the bytes loaded, so the save can skip an
 * unchanged cache. */
static size_t vk_pcache_load(struct geist_backend *be, struct vk_state *st, const char *path) {
    void  *data = nullptr;
    size_t size = 0;
    FILE  *f    = path != nullptr ? fopen(path, "rb") : nullptr;
    if (f != nullptr) {
        if (fseek(f, 0, SEEK_END) == 0) {
            const long end = ftell(f);
            /* ponytail: 64 MiB cap; ours is a few MiB */
            if (end > 0 && end <= (64L << 20) && fseek(f, 0, SEEK_SET) == 0) {
                data = geist_backend_alloc(be, (size_t) end, alignof(max_align_t));
                size = data != nullptr && fread(data, 1, (size_t) end, f) == (size_t) end
                               ? (size_t) end
                               : 0;
            }
        }
        fclose(f);
    }
    VkPipelineCacheCreateInfo ci = {.sType           = VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO,
                                    .initialDataSize = size,
                                    .pInitialData    = size != 0 ? data : nullptr};
    if (st->fn.CreatePipelineCache(st->device, &ci, nullptr, &st->pcache) != VK_SUCCESS) {
        ci.initialDataSize = 0; /* a driver may refuse data instead of ignoring it */
        ci.pInitialData    = nullptr;
        size               = 0;
        if (st->fn.CreatePipelineCache(st->device, &ci, nullptr, &st->pcache) != VK_SUCCESS) {
            st->pcache = VK_NULL_HANDLE;
        }
    }
    geist_backend_free(be, data);
    return size;
}

/* Writes the cache back when it changed, through a temporary file and a
 * rename so a concurrent reader never sees half of it. Failures are silent:
 * the cache only saves time. */
static void
vk_pcache_save(struct geist_backend *be, struct vk_state *st, const char *path, size_t loaded) {
    size_t size = 0;
    if (st->pcache == VK_NULL_HANDLE ||
        st->fn.GetPipelineCacheData(st->device, st->pcache, &size, nullptr) != VK_SUCCESS ||
        size == 0 || size == loaded) {
        return;
    }
    void *data = geist_backend_alloc(be, size, alignof(max_align_t));
    char  tmp[1100];
    if (data != nullptr &&
        st->fn.GetPipelineCacheData(st->device, st->pcache, &size, data) == VK_SUCCESS &&
        (size_t) snprintf(tmp, sizeof tmp, "%s.%ld.tmp", path, (long) getpid()) < sizeof tmp) {
        FILE *f  = fopen(tmp, "wb");
        bool  ok = f != nullptr && fwrite(data, 1, size, f) == size;
        if (f != nullptr) {
            ok = fclose(f) == 0 && ok;
        }
        if (!ok || rename(tmp, path) != 0) {
            (void) remove(tmp);
        }
    }
    geist_backend_free(be, data);
}

[[nodiscard]] enum geist_status vk_create_pipelines(struct geist_backend *be, struct vk_state *st) {
    /* Set/pipeline layouts for 2..VK_MAX_BINDINGS storage-buffer bindings;
     * every shader declares a push block within the shared 128-byte range. */
    for (uint32_t n = 2; n <= VK_MAX_BINDINGS; ++n) {
        VkDescriptorSetLayoutBinding bindings[VK_MAX_BINDINGS];
        for (uint32_t i = 0; i < n; ++i) {
            bindings[i] = (VkDescriptorSetLayoutBinding) {
                    .binding         = i,
                    .descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                    .descriptorCount = 1,
                    .stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT};
        }
        VkDescriptorSetLayoutCreateInfo linfo = {
                .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
                .bindingCount = n,
                .pBindings    = bindings};
        if (st->fn.CreateDescriptorSetLayout(
                    st->device, &linfo, nullptr, &st->seq_dlayouts[n - 2]) != VK_SUCCESS) {
            geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: descriptor layout failed");
            return GEIST_E_BACKEND;
        }
        VkPushConstantRange        push   = {.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
                                             .size       = VK_PUSH_RANGE};
        VkPipelineLayoutCreateInfo plinfo = {.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
                                             .setLayoutCount         = 1,
                                             .pSetLayouts            = &st->seq_dlayouts[n - 2],
                                             .pushConstantRangeCount = 1,
                                             .pPushConstantRanges    = &push};
        if (st->fn.CreatePipelineLayout(st->device, &plinfo, nullptr, &st->seq_playouts[n - 2]) !=
            VK_SUCCESS) {
            geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: pipeline layout failed");
            return GEIST_E_BACKEND;
        }
    }
    VkDescriptorPoolSize       psize  = {.type            = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                         .descriptorCount = VK_SEQ_MAX_SETS * VK_MAX_BINDINGS};
    VkDescriptorPoolCreateInfo dpinfo = {.sType   = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
                                         .maxSets = VK_SEQ_MAX_SETS,
                                         .poolSizeCount = 1,
                                         .pPoolSizes    = &psize};
    if (st->fn.CreateDescriptorPool(st->device, &dpinfo, nullptr, &st->seq_pool) != VK_SUCCESS) {
        geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: descriptor pool failed");
        return GEIST_E_BACKEND;
    }
    VkDescriptorPoolSize       csize  = {.type            = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                         .descriptorCount = VK_DSET_CACHE * VK_MAX_BINDINGS};
    VkDescriptorPoolCreateInfo dcinfo = {.sType   = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
                                         .maxSets = VK_DSET_CACHE,
                                         .poolSizeCount = 1,
                                         .pPoolSizes    = &csize};
    if (st->fn.CreateDescriptorPool(st->device, &dcinfo, nullptr, &st->dset_cache_pool) !=
        VK_SUCCESS) {
        geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: dset cache pool failed");
        return GEIST_E_BACKEND;
    }
    VkCommandBufferAllocateInfo cainfo = {.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
                                          .commandPool        = st->cmd_pool,
                                          .level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
                                          .commandBufferCount = VK_SEQ_CMDBUFS};
    if (st->fn.AllocateCommandBuffers(st->device, &cainfo, st->seq_cmds) != VK_SUCCESS) {
        geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: seq command buffers failed");
        return GEIST_E_BACKEND;
    }
    VkFenceCreateInfo finfo = {.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    if (st->fn.CreateFence(st->device, &finfo, nullptr, &st->seq_fence) != VK_SUCCESS) {
        geist_backend_set_error(be, GEIST_E_BACKEND, "vulkan: seq fence failed");
        return GEIST_E_BACKEND;
    }
    if (st->profile_enabled) {
        VkQueryPoolCreateInfo qinfo = {.sType      = VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO,
                                       .queryType  = VK_QUERY_TYPE_TIMESTAMP,
                                       .queryCount = VK_SEQ_MAX_DISPATCH + 8};
        if (st->fn.CreateQueryPool(st->device, &qinfo, nullptr, &st->ts_pool) != VK_SUCCESS) {
            st->profile_enabled = false; /* profiling is best-effort */
        }
    }

    static const struct {
        const uint32_t *code;
        size_t          bytes;
    } blobs[VK_PIPE_COUNT] = {
#define X(id, spv, name, nbind, kind) [id] = {spv, sizeof(spv)},
#include "vk_pipes.def"
#undef X
    };
    char         pcache_path[1100];
    const bool   use_pcache = vk_pcache_path(st, sizeof pcache_path, pcache_path);
    const size_t loaded     = vk_pcache_load(be, st, use_pcache ? pcache_path : nullptr);
    for (int i = 0; i < VK_PIPE_COUNT; ++i) {
        if (vk_pipe_needs_coopmat(i) && !st->has_coopmat) {
            continue; /* stays VK_NULL_HANDLE; linear_t falls back */
        }
        if (i == VK_PIPE_DN_SCAN && !st->dn_scan) {
            continue; /* stays VK_NULL_HANDLE; deltanet_mix runs deltanet_delta_f32 */
        }
        /* Full subgroups need local_size_x to be a multiple of 32; every
         * tiled GEMM is 128 or 256 wide, so a miss is a shader edit that
         * broke the assumption: fail loudly rather than loop matvecs. */
        const bool pin = st->sg32_pinnable && vk_pipe_is_tiled_gemm(i);
        if (pin && vk_spirv_local_size_x(blobs[i].bytes / 4u, blobs[i].code) % 32u != 0u) {
            geist_backend_set_error(be,
                                    GEIST_E_INTERNAL,
                                    "vulkan: pipeline %d is not a whole number of 32-lane "
                                    "subgroups",
                                    i);
            return GEIST_E_INTERNAL;
        }
        enum geist_status s = vk_make_pipeline(be,
                                               st,
                                               blobs[i].code,
                                               blobs[i].bytes,
                                               st->seq_playouts[vk_pipe_nbind[i] - 2],
                                               pin,
                                               &st->pipes[i]);
        if (s != GEIST_OK) {
            if (vk_pipe_needs_coopmat(i)) {
                fprintf(stderr,
                        "geist vulkan: coopmat pipeline unavailable — using the "
                        "register-tiled GEMM\n");
                st->pipes[i] = VK_NULL_HANDLE;
                continue;
            }
            return s;
        }
    }
    if (use_pcache) {
        vk_pcache_save(be, st, pcache_path, loaded);
    }
    return GEIST_OK;
}
