#!/usr/bin/env python3
# .github/workflows/ci.yml -> .gitea/workflows/ci.yml for the geisten org's runners.
# Run from the repository root after changing .github/workflows/ci.yml.
import re
s=open('.github/workflows/ci.yml').read()
# GitHub runs this for pull requests only; on Gitea it gates main as well
gh_on=s[s.index("# This repository on GitHub is the public mirror"):s.index("\n\n",s.index("\non:\n"))]
s=s.replace(gh_on,"""on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:""",1)
m=re.search(r"\n( +)# Intel Mac: target-mac\*\.mk[^\n]*\n(?:\1#[^\n]*\n)*\1- name: macOS x86_64\n\1  runner: macos-15-intel\n(?:\1  .*\n)+",s)
assert m, "intel entry"
s=s[:m.start()]+"\n"+s[m.end():]
assert "macos-15-intel" not in s and "vulkan-gpu:" not in s
a=s.index("  format:\n"); s=s[:a]+s[a:].replace("    runs-on: ubuntu-24.04-arm\n","    runs-on: ubuntu-24.04\n",1)
a=s.index("  tsan:\n")
s=s[:a]+s[a:].replace("    runs-on: ubuntu-24.04\n","""    # desktop-tsan: its containers may call personality(ADDR_NO_RANDOMIZE), so
    # setarch -R runs the binaries without ASLR — gcc-14's TSan aborts on the
    # host's 32-bit mmap entropy ("unexpected memory mapping")
    runs-on: ubuntu-24.04-tsan
""",1)
m0=s.index("Multi-session tests under TSan",a); e=s.index("\n\n",m0)
seg=s[m0:e]
for t in ["bin/linux/tsan/tests/test_multi_session_parallel_int","bin/linux/tsan/tests/test_session_cancel_unit","bin/linux/tsan/tests/test_par_for_unit"]:
    seg=seg.replace(t,'setarch "$(uname -m)" -R '+t,1)
assert seg.count("setarch")==3
s=s[:m0]+seg+s[e:]
hdr="""# Gitea copy of .github/workflows/ci.yml, regenerated by scripts/gitea-ci.py
# when that file changes. Runners of the geisten org: ubuntu-24.04 = desktop
# (docker, 4 parallel), ubuntu-24.04-tsan = desktop (docker, see the tsan
# job), ubuntu-24.04-arm = Pi 5 (docker, one job at a time under the board
# lock), macos-15 = the M1 Max (host). No Intel Mac leg; the hardware tier is
# in its own workflows here (docs/HARDWARE_CI.md).
"""
open('.gitea/workflows/ci.yml','w').write(hdr+s)
