#!/bin/sh
# Render the Homebrew formula for the geisten/homebrew-tap repo.
# Used by .github/workflows/release.yml (homebrew job) on every version tag.
#
#   make-brew-formula.sh <version> <sha-macos-arm64> <sha-linux-arm64> <sha-linux-x86_64> > geist.rb
set -eu
[ $# -eq 4 ] || { echo "usage: $0 <version> <sha-mac> <sha-linux-arm64> <sha-linux-x86_64>" >&2; exit 1; }
V=$1 SHA_MAC=$2 SHA_ARM=$3 SHA_X86=$4
BASE="https://github.com/geisten/geistlib/releases/download/v$V"

cat <<EOF
# Auto-generated by geisten/geistlib scripts/make-brew-formula.sh on release — do not edit here.
class Geist < Formula
  desc "CPU-first LLM inference engine — single dependency-free binary (GGUF)"
  homepage "https://github.com/geisten/geistlib"
  version "$V"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$BASE/geist-macos-arm64.tar.gz"
      sha256 "$SHA_MAC"
    end
  end
  on_linux do
    on_arm do
      url "$BASE/geist-linux-arm64.tar.gz"
      sha256 "$SHA_ARM"
    end
    on_intel do
      url "$BASE/geist-linux-x86_64.tar.gz"
      sha256 "$SHA_X86"
    end
  end

  def install
    bin.install "geist"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/geist --version")
  end
end
EOF
